IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CLIENTES_BANCA')
    DROP TABLE CLIENTES_BANCA

CREATE TABLE CLIENTES_BANCA
(
  NoCuenta VARCHAR(5) not null CONSTRAINT pkNoCuenta PRIMARY KEY,
  Nombre VARCHAR(30),
  Saldo NUMERIC(8,2)
)

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TIPOS_MOVIMIENTO')
    DROP TABLE TIPOS_MOVIMIENTO

CREATE TABLE TIPOS_MOVIMIENTO
(
  ClaveM VARCHAR(2) not null CONSTRAINT pkClaveM PRIMARY KEY,
  Descripcion VARCHAR(30)
)

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'MOVIMIENTOS')
    DROP TABLE MOVIMIENTOS

CREATE TABLE MOVIMIENTOS
(
  NoCuenta VARCHAR(5) NOT NULL CONSTRAINT fkNoCuenta FOREIGN KEY REFERENCES CLIENTES_BANCA(NoCuenta),
  ClaveM VARCHAR(2) NOT NULL CONSTRAINT fkClaveM FOREIGN KEY REFERENCES TIPOS_MOVIMIENTO(ClaveM),
  Fecha DATETIME NOT NULL,
  Monto NUMERIC(10,2)
)

ALTER TABLE MOVIMIENTOS ADD CONSTRAINT pkMovimientos PRIMARY KEY (NoCuenta,ClaveM,Fecha)

BEGIN TRANSACTION PRUEBA1
INSERT INTO CLIENTES_BANCA VALUES('001', 'Manuel Rios Maldonado', 9000);
INSERT INTO CLIENTES_BANCA VALUES('002', 'Pablo Perez Ortiz', 5000);
INSERT INTO CLIENTES_BANCA VALUES('003', 'Luis Flores Alvarado', 8000);
COMMIT TRANSACTION PRUEBA1

SELECT * FROM CLIENTES_BANCA

BEGIN TRANSACTION PRUEBA2
INSERT INTO CLIENTES_BANCA VALUES('004','Ricardo Rios Maldonado',19000)
INSERT INTO CLIENTES_BANCA VALUES('005','Pablo Ortiz Arana',15000)
INSERT INTO CLIENTES_BANCA VALUES('006','Luis Manuel Alvarado',18000)

ROLLBACK TRANSACTION PRUEBA2

BEGIN TRANSACTION PRUEBA3
INSERT INTO TIPOS_MOVIMIENTO VALUES('A','Retiro Cajero Automatico');
INSERT INTO TIPOS_MOVIMIENTO VALUES('B','Deposito Ventanilla');
COMMIT TRANSACTION PRUEBA3


BEGIN TRANSACTION PRUEBA4
INSERT INTO MOVIMIENTOS VALUES('001','A',GETDATE(),500);
UPDATE CLIENTES_BANCA SET SALDO = SALDO -500
WHERE NoCuenta='001'
COMMIT TRANSACTION PRUEBA4

BEGIN TRANSACTION PRUEBA5
INSERT INTO CLIENTES_BANCA VALUES('005','Rosa Ruiz Maldonado',9000);
INSERT INTO CLIENTES_BANCA VALUES('006','Luis Camino Ortiz',5000);
INSERT INTO CLIENTES_BANCA VALUES('001','Oscar Perez Alvarado',8000);

IF @@ERROR = 0
COMMIT TRANSACTION PRUEBA5
ELSE
BEGIN
PRINT 'A transaction needs to be rolled back'
ROLLBACK TRANSACTION PRUEBA5
END

IF EXISTS (SELECT name FROM sysobjects WHERE name = 'REGISTRAR_RETIRO_CAJERO' AND type = 'P')
                DROP PROCEDURE REGISTRAR_RETIRO_CAJERO
            GO

            CREATE PROCEDURE REGISTRAR_RETIRO_CAJERO
                @NoCuenta VARCHAR(5),
                @Monto NUMERIC(10,2)
            AS
                BEGIN TRANSACTION PRUEBA6
                INSERT INTO MOVIMIENTOS VALUES(@NoCuenta,'A',GETDATE(),@Monto);
                UPDATE CLIENTES_BANCA SET SALDO = SALDO -@Monto
                WHERE NoCuenta=@NoCuenta

                IF @@ERROR = 0
                COMMIT TRANSACTION PRUEBA6
                ELSE
                BEGIN
                PRINT 'A transaction needs to be rolled back'
                ROLLBACK TRANSACTION PRUEBA6
                END

  EXECUTE REGISTRAR_RETIRO_CAJERO '002',800